/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spellcheck;

import java.util.List;
import org.languagetool.JLanguageTool;
import org.languagetool.Language;
import org.languagetool.language.BritishEnglish;
import org.languagetool.rules.Rule;
import org.languagetool.rules.RuleMatch;

import java.io.IOException;


public class App {

    public String getGreeting() throws IOException{

      String text = "Hellow orld";
      System.out.println("Original text: " + text);

      JLanguageTool langTool = new JLanguageTool(new BritishEnglish());
      for (Rule rule : langTool.getAllRules()) {
        if (!rule.isDictionaryBasedSpellingRule()) {
          langTool.disableRule(rule.getId());
        }
      }

      List<RuleMatch> matches = langTool.check(text);
      for (RuleMatch match : matches) {
        System.out.println("Potential typo at characters " +
            match.getFromPos() + "-" + match.getToPos() + ": " +
            match.getMessage());
        System.out.println("Suggested correction(s): " +
            match.getSuggestedReplacements());
            text = text.replace(text.substring(match.getFromPos(), match.getToPos()), match.getSuggestedReplacements().get(0).toString());
      }
      System.out.print("Fixed: ");

        return text;
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
    }
}
